services:
  chatbot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      OPENWEATHER_API_KEY: "${OPENWEATHER_API_KEY}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      FLIGHTAWARE_API_KEY: "${FLIGHTAWARE_API_KEY}"
      REDIS_URL: "redis://redis:6379/0"
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data:
